const state={catalog:[],competitors:[],rules:[],filtered:[],cart:new Map(),fav:new Set(JSON.parse(localStorage.getItem('mmeColumnFavorites')||'[]')),view:'cards',page:1,pageSize:50,tableFilters:{},expanded:new Set(),wizard:{}};
const fields=['category','packing','phase','particle','pore','diameter','length'];
const filterIds={category:'categoryFilter',packing:'packingFilter',phase:'phaseFilter',particle:'particleFilter',pore:'poreFilter',diameter:'diameterFilter',length:'lengthFilter'};
const tableFields=['name','code','category','packing','phase','particle','pore','diameter','length','applications'];
const quoteEmail='sales@almurtaja.com',quoteWhatsapp='962000000000';
const $=s=>document.querySelector(s), norm=v=>String(v||'').toLowerCase().replace(/[µμ]/g,'u').replace(/å/g,'a').replace(/angstroms?|ang\b/g,'a').replace(/[^a-z0-9.+%*-]+/g,' ').replace(/\s+/g,' ').trim();
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const n=v=>Number(String(v||'').replace(/[^0-9.]/g,''))||0, sortNat=(a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:'base'});
const unique=f=>[...new Set(state.catalog.map(x=>x[f]).filter(Boolean))].sort(sortNat);
function pore(v){let m=String(v||'').match(/\d+/);return m?Number(m[0]):0}
function phaseGroup(v){let x=norm(v);if(['c18','ods','ods2','aq c18'].some(p=>x.includes(p)))return'C18';if(x.includes('c8'))return'C8';if(x.includes('phenyl'))return'Phenyl';if(x.includes('pfp'))return'PFP';if(x.includes('biphenyl'))return'Biphenyl';if(x.includes('hilic'))return'HILIC';if(x.includes('amide'))return'Amide';if(x.includes('nh2')||x.includes('amino'))return'NH2';if(x.includes('cn')||x.includes('cyano'))return'CN';if(x.includes('sec'))return'SEC';return v||''}
function productText(p){let uses=getUses(p);return norm(`${p.name} ${p.code} ${p.category} ${p.packing} ${p.phase} ${p.particle} ${p.pore} ${p.diameter} ${p.length} ${p.search||''} ${uses.map(u=>`${u.label} ${u.arabic} ${u.searchTerms?.join(' ')} ${u.reason}`).join(' ')}`)}
function ruleMatches(p,r){let m=r.match||{};let has=(f,vals)=>!vals||!vals.length||vals.includes(p[f]);if(!has('category',m.category)||!has('phase',m.phase)||!has('particle',m.particle)||!has('diameter',m.diameter)||!has('length',m.length))return false;if(m.poreMin&&pore(p.pore)<m.poreMin)return false;if(m.particleMax&&n(p.particle)>m.particleMax)return false;if(m.diameterMin&&n(p.diameter)<m.diameterMin)return false;if(m.categoryContains&&!m.categoryContains.some(x=>norm(p.category).includes(norm(x))))return false;if(m.packingContains&&!m.packingContains.some(x=>norm(p.packing).includes(norm(x))||norm(p.name).includes(norm(x))))return false;return true}
function getUses(p){return state.rules.filter(r=>ruleMatches(p,r)).slice(0,4)}
function useScore(p,terms){let uses=getUses(p);let txt=norm(uses.map(u=>`${u.label} ${u.arabic} ${u.searchTerms?.join(' ')} ${u.reason}`).join(' '));return terms.reduce((s,t)=>s+(txt.includes(t)?45:0),0)}
function scoreProduct(p,terms){if(!terms.length)return boost(p);let hay=productText(p),score=useScore(p,terms);for(const t of terms){if(!hay.includes(t))return 0;if(norm(p.code).includes(t))score+=100;else if(norm(p.phase).includes(t))score+=40;else if(norm(p.name).includes(t))score+=25;else if(norm(p.packing).includes(t))score+=15;else score+=5}return score+boost(p)}
function boost(p){return 1+(p.category==='Analytical column'?8:0)+(p.particle==='5'?5:0)+(p.diameter==='4.6'?3:0)+(['150','250'].includes(p.length)?2:0)}
async function init(){try{let [catalog,seed,rules]=await Promise.all([fetch('data/catalog.json').then(r=>r.json()),fetch('data/competitor-columns.json').then(r=>r.json()).catch(()=>[]),fetch('data/application-rules.json').then(r=>r.json()).catch(()=>[])]);state.catalog=catalog;state.rules=rules;state.competitors=[...(window.VERIFIED_COMPETITOR_ROWS||[]),...seed];state.pageSize=Number($('#pageSizeSelect')?.value||50);setupFilters();setupWizard();bind();applyFilters();console.log('Verified competitor rows',window.VERIFIED_COMPETITOR_COUNTS||{});}catch(e){console.error(e);$('#resultCount').textContent='Catalog could not be loaded.'}}
function bind(){$('#searchInput')?.addEventListener('input',()=>{state.page=1;applyFilters();renderReplacementMatches()});$('#replacementInput')?.addEventListener('input',renderReplacementMatches);$('#sortSelect')?.addEventListener('change',()=>{state.page=1;renderProducts()});$('#pageSizeSelect')?.addEventListener('change',e=>{state.pageSize=Number(e.target.value);state.page=1;renderProducts()});$('#clearFilters')?.addEventListener('click',clearFilters);$('#quoteButton')?.addEventListener('click',openCheckout);$('#copyQuote')?.addEventListener('click',copyQuote);$('#submitQuote')?.addEventListener('click',submitEmail);$('#whatsappQuote')?.addEventListener('click',submitWhats);document.querySelectorAll('.view-button').forEach(b=>b.onclick=()=>setView(b.dataset.view));fields.forEach(f=>document.getElementById(filterIds[f])?.addEventListener('change',()=>{state.page=1;applyFilters()}));$('#loadMore')?.setAttribute('hidden','hidden')}
function setupFilters(){fields.forEach(f=>{let s=document.getElementById(filterIds[f]);if(!s)return;s.innerHTML=`<option value="">All ${f}</option>`;unique(f).forEach(v=>s.append(new Option(v,v)))});$('#statProducts').textContent=state.catalog.length.toLocaleString();$('#statPackings').textContent=unique('packing').length;$('#statPhases').textContent=`${unique('phase').length}+`}
function applyFilters(){let q=$('#searchInput')?.value.trim()||'', terms=norm(q).split(' ').filter(Boolean), sel=Object.fromEntries(fields.map(f=>[f,document.getElementById(filterIds[f])?.value||'']));state.filtered=state.catalog.map(item=>({item,score:scoreProduct(item,terms)})).filter(({item,score})=>fields.every(f=>!sel[f]||item[f]===sel[f])&&(!terms.length||score>0)&&passWizard(item)&&passTableFilters(item));renderExpert(q,terms);renderActive(sel,terms);renderProducts()}
function passWizard(p){return Object.values(state.wizard).every(c=>!c?.rules||Object.entries(c.rules).every(([f,vs])=>!vs?.length||vs.includes(p[f])))}
function passTableFilters(p){return Object.entries(state.tableFilters).every(([f,v])=>!v||(f==='applications'?norm(getUses(p).map(x=>x.label+' '+x.arabic).join(' ')).includes(norm(v)):norm(p[f]).includes(norm(v))))}
function sorted(){let s=$('#sortSelect')?.value||'relevance';return[...state.filtered].sort((a,b)=>s==='relevance'?b.score-a.score||sortNat(a.item.name,b.item.name):s==='particle'?n(a.item.particle)-n(b.item.particle)||sortNat(a.item.name,b.item.name):s==='length'?n(a.item.length)-n(b.item.length)||sortNat(a.item.name,b.item.name):sortNat(a.item.name,b.item.name))}
function pageRows(rows){let totalPages=Math.max(1,Math.ceil(rows.length/state.pageSize));state.page=Math.min(Math.max(1,state.page),totalPages);let start=(state.page-1)*state.pageSize;return{shown:rows.slice(start,start+state.pageSize),totalPages,start}}
function renderProducts(){let grid=$('#productGrid'),all=sorted(),{shown,totalPages,start}=pageRows(all);grid.innerHTML='';grid.className=`product-grid ${state.view}-view`;if($('#tableColumnFilters'))$('#tableColumnFilters').hidden=state.view!=='table';if(state.view==='table'){renderTableFilters();renderTable(grid,shown)}else if(state.view==='compact')renderCompact(grid,all);else shown.forEach(r=>grid.append(card(r.item)));$('#resultCount').textContent=`${all.length.toLocaleString()} matching columns · showing ${all.length?start+1:0}-${Math.min(start+state.pageSize,all.length)} · ${state.pageSize} per page`;renderPages(totalPages)}
function renderPages(totalPages){let h=$('#pagination');if(!h)return;if(totalPages<=1){h.innerHTML='';return}let pages=new Set([1,totalPages,state.page-1,state.page,state.page+1]);let html=`<button ${state.page===1?'disabled':''} onclick="goToPage(${state.page-1})">Prev</button>`;[...pages].filter(p=>p>=1&&p<=totalPages).sort((a,b)=>a-b).forEach((p,i,a)=>{if(i&&p-a[i-1]>1)html+='<span>...</span>';html+=`<button class="${p===state.page?'active':''}" onclick="goToPage(${p})">${p}</button>`});h.innerHTML=html+`<button ${state.page===totalPages?'disabled':''} onclick="goToPage(${state.page+1})">Next</button>`}
window.goToPage=p=>{state.page=p;renderProducts();document.getElementById('catalog')?.scrollIntoView({behavior:'smooth',block:'start'})};
function badges(p){return getUses(p).slice(0,3).map(u=>`<span class="use-badge" title="${esc(u.arabic)} — ${esc(u.reason)}">${esc(u.label)}</span>`).join('')}
function card(p){let c=document.createElement('article');c.className='product-card upgraded-card';c.innerHTML=`<div class="column-art ${norm(p.category).includes('prep')?'prep-art':norm(p.category).includes('guard')?'guard-art':'analytical-art'}">${columnSvg(p)}</div><div class="product-top"><span class="category">${esc(p.category)}</span><div class="quick-actions"><button class="icon-button favorite ${state.fav.has(p.id)?'active':''}" type="button">♡</button></div></div><p class="code">Code ${esc(p.code)}</p><h3>${esc(p.name)}</h3><div class="use-badges">${badges(p)}</div><dl class="specs icon-specs">${specHtml(p)}</dl><button class="button product-quote">Add to quote</button>`;c.querySelector('.favorite').onclick=()=>toggleFav(p);c.querySelector('.product-quote').onclick=()=>addCart(p);return c}
function columnSvg(p){let ph=norm(p.phase).replace(/[^a-z0-9]/g,''),long=n(p.length)>=200,wide=n(p.diameter)>=10,dots=Math.max(3,Math.min(12,Math.round(30/Math.max(2,n(p.particle)||5))));return`<svg viewBox="0 0 220 84"><rect class="tube ${ph}" x="${wide?22:42}" y="30" width="${long?156:120}" height="24" rx="12"/><rect class="cap" x="24" y="25" width="24" height="34" rx="8"/><rect class="cap" x="174" y="25" width="24" height="34" rx="8"/>${Array.from({length:dots}).map((_,i)=>`<circle class="particle-dot" cx="${62+i*10}" cy="42" r="2.5"/>`).join('')}<text x="110" y="75" text-anchor="middle">${esc(p.phase)} · ${esc(p.particle)}um · ${esc(p.diameter)}x${esc(p.length)}</text></svg>`}
function specHtml(p){return[['⚗','Phase',p.phase],['▧','Packing',p.packing],['●','Particle',`${p.particle||'-'} um`],['◌','Pore',p.pore||'-'],['↔','ID',`${p.diameter||'-'} mm`],['━','Length',`${p.length||'-'} mm`]].map(([i,l,v])=>`<div><dt><span class="spec-icon">${i}</span>${l}</dt><dd>${esc(v)}</dd></div>`).join('')}
function renderTableFilters(){let h=$('#tableColumnFilters');h.hidden=false;h.innerHTML=tableFields.map(f=>`<label>${f}<input type="search" value="${esc(state.tableFilters[f]||'')}" placeholder="Filter ${f}" data-table-filter="${f}"></label>`).join('');h.querySelectorAll('input').forEach(inp=>inp.oninput=()=>{state.tableFilters[inp.dataset.tableFilter]=inp.value;state.page=1;applyFilters()})}
function renderTable(h,rows){h.innerHTML=`<div class="table-wrap"><table class="product-table"><thead><tr><th>Product</th><th>Code</th><th>Category</th><th>Packing</th><th>Phase</th><th>Applications</th><th>Particle</th><th>Pore</th><th>ID</th><th>Length</th><th>Actions</th></tr></thead><tbody>${rows.map(r=>row(r.item)).join('')}</tbody></table></div>`}
function row(p){return`<tr><td>${esc(p.name)}</td><td>${esc(p.code)}</td><td>${esc(p.category)}</td><td>${esc(p.packing)}</td><td>${esc(p.phase)}</td><td>${badges(p)}</td><td>${esc(p.particle)} um</td><td>${esc(p.pore||'-')}</td><td>${esc(p.diameter)} mm</td><td>${esc(p.length)} mm</td><td class="table-actions"><button onclick="toggleFavoriteById('${p.id}')">${state.fav.has(p.id)?'Saved':'Favorite'}</button><button onclick="addToCartById('${p.id}')">Quote</button></td></tr>`}
function renderCompact(h,rows){let g=new Map();rows.forEach(({item,score})=>{let k=[item.category,item.packing,item.phase].map(norm).join('|');if(!g.has(k))g.set(k,{base:item,score,variants:[]});g.get(k).variants.push(item)});let gr=[...g.entries()].sort((a,b)=>b[1].score-a[1].score),{shown,totalPages,start}=pageRows(gr);h.innerHTML=shown.map(([k,x])=>compactHtml(k,x)).join('');$('#resultCount').textContent=`${gr.length.toLocaleString()} column families · showing ${gr.length?start+1:0}-${Math.min(start+state.pageSize,gr.length)} · ${state.pageSize} per page`;renderPages(totalPages)}
function cv(items,f){let vs=[...new Set(items.map(i=>i[f]).filter(Boolean))].sort(sortNat);return vs.length<=4?vs.join(', '):`${vs[0]}-${vs[vs.length-1]}`}
function compactHtml(k,g){let ex=state.expanded.has(k);return`<article class="compact-row ${ex?'expanded':''}"><div><strong>${esc(g.base.packing)} ${esc(g.base.phase)}</strong><span>${g.variants.length} variants · ${esc(g.base.category)}</span><div class="use-badges">${badges(g.base)}</div></div><div class="compact-specs"><span>${cv(g.variants,'particle')} um</span><span>${cv(g.variants,'pore')}</span><span>ID ${cv(g.variants,'diameter')} mm</span><span>${cv(g.variants,'length')} mm</span></div><button class="button ghost" onclick="toggleCompactGroup('${encodeURIComponent(k)}')">${ex?'Hide variants':'View variants'}</button>${ex?`<div class="compact-variants"><table class="product-table"><thead><tr><th>Product</th><th>Code</th><th>Apps</th><th>Particle</th><th>Pore</th><th>ID</th><th>Length</th><th>Actions</th></tr></thead><tbody>${g.variants.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.code)}</td><td>${badges(p)}</td><td>${esc(p.particle)} um</td><td>${esc(p.pore||'-')}</td><td>${esc(p.diameter)} mm</td><td>${esc(p.length)} mm</td><td class="table-actions"><button onclick="toggleFavoriteById('${p.id}')">${state.fav.has(p.id)?'Saved':'Favorite'}</button><button onclick="addToCartById('${p.id}')">Quote</button></td></tr>`).join('')}</tbody></table></div>`:''}</article>`}
window.toggleCompactGroup=e=>{let k=decodeURIComponent(e);state.expanded.has(k)?state.expanded.delete(k):state.expanded.add(k);renderProducts()};
function setView(v){state.view=v;state.page=1;document.querySelectorAll('.view-button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderProducts()}
const wizardQuestions=[{key:'mode',title:'What type of separation do you need?',choices:[{label:'General reverse phase',help:'Small molecules and routine pharma methods.',rules:{phase:['C18','C8','ODS','ODS2','AQ-C18']}},{label:'Polar / HILIC',help:'Polar, hydrophilic or high-aqueous methods.',rules:{phase:['HILIC','Amide','Diol','NH2','NH2-S','CN','AQ-C18']}},{label:'Peptides / proteins',help:'Biomolecule screening options.',rules:{phase:['C4','SEC','HIC','Protein A','C18','C8','Amide','HILIC']}},{label:'Sugars',help:'Carbohydrate screening options.',rules:{phase:['Sugar','NH2','NH2-S','Amide']}},{label:'Aromatics / isomers',help:'Phenyl, PFP and biphenyl selectivity.',rules:{phase:['Phenyl','Phenyl-Hexyl','PFP','Biphenyl']}}]},{key:'format',title:'Which format is needed?',choices:[{label:'Analytical',help:'Routine HPLC/UHPLC.',rules:{category:['Analytical column']}},{label:'Guard',help:'Column protection.',rules:{category:['Analytical guard column','prep guard column']}},{label:'Prep',help:'Purification/loading.',rules:{category:['Prep Column','prep guard column']}},{label:'Not sure',help:'Keep all formats.',rules:{}}]},{key:'performance',title:'What matters most?',choices:[{label:'Fast UHPLC',help:'Small particles.',rules:{particle:['1.7','1.8','1.9','2.5','2.6','2.7','3']}},{label:'Routine robust HPLC',help:'5 µm columns.',rules:{particle:['5']}},{label:'Wide-pore biomolecule',help:'300 Å+ pores.',rules:{pore:['300Å','500Å','1000Å','2000Å']}},{label:'No preference',help:'Keep all.',rules:{}}]}];
function setupWizard(){let h=$('#wizardSteps');if(h)h.innerHTML=wizardQuestions.map((q,i)=>`<div class="step ${i===0?'active':''}" data-wizard-step="${i}"><span>${i+1}</span><div><strong>${esc(q.title)}</strong><p>${state.wizard[q.key]?.label||'Choose option'}</p></div></div>`).join('');renderWizardQuestion(0)}
function renderWizardQuestion(i){state.wizardIndex=Math.max(0,Math.min(i,wizardQuestions.length-1));let h=$('#wizardQuestion'),q=wizardQuestions[state.wizardIndex];if(!h)return;h.innerHTML=`<div class="question-block"><h3>${esc(q.title)}</h3><div class="choice-grid">${q.choices.map((c,j)=>`<button class="choice ${state.wizard[q.key]?.label===c.label?'selected':''}" onclick="chooseWizard(${state.wizardIndex},${j})"><strong>${esc(c.label)}</strong><span>${esc(c.help)}</span></button>`).join('')}</div></div>`;document.querySelectorAll('[data-wizard-step]').forEach(s=>s.classList.toggle('active',Number(s.dataset.wizardStep)===state.wizardIndex))}
window.chooseWizard=(qi,ci)=>{let q=wizardQuestions[qi];state.wizard[q.key]=q.choices[ci];state.page=1;setupWizard();renderWizardQuestion(Math.min(qi+1,wizardQuestions.length-1));applyFilters()};window.nextWizardStep=()=>renderWizardQuestion((state.wizardIndex||0)+1);window.previousWizardStep=()=>renderWizardQuestion((state.wizardIndex||0)-1);window.resetWizard=()=>{state.wizard={};state.page=1;setupWizard();applyFilters()};
function clearFilters(){$('#searchInput').value='';fields.forEach(f=>{let s=document.getElementById(filterIds[f]);if(s)s.value=''});state.tableFilters={};state.page=1;applyFilters()}
function addCart(p){let x=state.cart.get(p.id)||{product:p,qty:0};x.qty++;state.cart.set(p.id,x);renderCart()}function addToCartById(id){let p=state.catalog.find(i=>i.id===String(id));if(p)addCart(p)}function toggleFav(p){state.fav.has(p.id)?state.fav.delete(p.id):state.fav.add(p.id);localStorage.setItem('mmeColumnFavorites',JSON.stringify([...state.fav]));renderProducts()}function toggleFavoriteById(id){let p=state.catalog.find(i=>i.id===String(id));if(p)toggleFav(p)}window.addToCartById=addToCartById;window.toggleFavoriteById=toggleFavoriteById;
function renderCart(){let h=$('#cartItems');if(!h)return;if(!state.cart.size){h.innerHTML='<span class="muted">No products selected yet.</span>';return}h.innerHTML=[...state.cart.values()].map(({product:p,qty})=>`<span class="cart-item"><strong>${esc(p.code)}</strong><label>Qty <input type="number" min="1" value="${qty}" onchange="setCartQty('${p.id}',this.value)"></label><button onclick="removeCartItem('${p.id}')">×</button></span>`).join('')}window.setCartQty=(id,qty)=>{let x=state.cart.get(id);if(x){x.qty=Math.max(1,Number(qty)||1);renderCart()}};window.removeCartItem=id=>{state.cart.delete(id);renderCart()};
function checkoutText(){let lines=['MME column quotation request','','Selected products:'];[...state.cart.values()].forEach(({product:p,qty},i)=>lines.push(`${i+1}. ${p.code} | ${p.name} | ${p.phase} | ${p.particle}um | ${p.diameter}x${p.length}mm | Qty ${qty}`));lines.push('',`Name: ${$('#customerName')?.value||''}`,`Company: ${$('#customerCompany')?.value||''}`,`Email: ${$('#customerEmail')?.value||''}`,`Phone: ${$('#customerPhone')?.value||''}`,`Notes: ${$('#customerNotes')?.value||''}`);return lines.join('\n')}
function openCheckout(){if(!state.cart.size){alert('Please add at least one product to the quote basket.');return}let l=$('#checkoutList');if(l)l.innerHTML=[...state.cart.values()].map(({product:p,qty})=>`<div class="checkout-item"><strong>${esc(p.code)}</strong><span>${esc(p.name)}</span><em>Qty ${qty}</em></div>`).join('');let m=$('#quoteModal');m?.showModal?m.showModal():alert(checkoutText())}function copyQuote(){navigator.clipboard?.writeText(checkoutText());alert('Quotation request copied.')}function submitEmail(){location.href=`mailto:${quoteEmail}?subject=${encodeURIComponent('MME column quotation request')}&body=${encodeURIComponent(checkoutText())}`}function submitWhats(){open(`https://wa.me/${quoteWhatsapp}?text=${encodeURIComponent(checkoutText())}`,'_blank')}
function competitorText(c){return norm(`${c.brand} ${c.family} ${c.name} ${c.partNumber||''} ${(c.aliases||[]).join(' ')} ${c.phase} ${c.particle} ${c.pore} ${c.diameter} ${c.length} ${c.mode}`)}
function findCompetitorMatches(q){let terms=norm(q).split(' ').filter(Boolean);if(!terms.length)return[];return state.competitors.map(c=>({c,score:terms.reduce((s,t)=>s+(competitorText(c).includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,6)}
function matchDetails(c,p){let d=[];let same=(l,a,b,pts)=>{let ok=norm(a)===norm(b);d.push({l,a:a||'-',b:b||'-',ok,pts:ok?pts:0})};let close=(l,a,b,pts,tol)=>{let aa=n(a),bb=n(b),ok=aa&&bb&&Math.abs(aa-bb)<=tol;d.push({l,a:a||'-',b:b||'-',ok,pts:ok?pts:Math.max(0,pts-Math.abs(aa-bb)*2)})};same('Phase group',phaseGroup(c.phase),phaseGroup(p.phase),35);close('Particle size',c.particle,p.particle,18,.4);let po=pore(c.pore)&&pore(p.pore)&&Math.abs(pore(c.pore)-pore(p.pore))<=35;d.push({l:'Pore size',a:c.pore||'-',b:p.pore||'-',ok:po,pts:po?12:0});close('ID',c.diameter,p.diameter,15,.4);close('Length',c.length,p.length,15,10);let fmt=(norm(c.mode).includes('prep')&&norm(p.category).includes('prep'))||(!norm(c.mode).includes('prep')&&norm(p.category).includes('analytical'));d.push({l:'Format',a:c.mode||'-',b:p.category||'-',ok:fmt,pts:fmt?5:0});return d}
function bestEquivalent(c){let all=state.catalog.map(p=>{let details=matchDetails(c,p),score=details.reduce((s,x)=>s+x.pts,0);return{p,details,score,percent:Math.max(0,Math.min(99,Math.round(score)))}}).sort((a,b)=>b.score-a.score);return all[0]}
function comparison(c,b){return`<div class="equiv-summary"><span class="match-score">${b.percent}% match</span><strong>Closest MME: ${esc(b.p.code)} - ${esc(b.p.name)}</strong><button class="button ghost" onclick="addToCartById('${b.p.id}')">Add MME column to quote</button></div><table class="product-table compare-equivalent"><thead><tr><th>Specification</th><th>${esc(c.brand)} column</th><th>MME equivalent</th><th>Match</th></tr></thead><tbody>${b.details.map(r=>`<tr class="${r.ok?'spec-match':'spec-gap'}"><td>${esc(r.l)}</td><td>${esc(r.a)}</td><td>${esc(r.b)}</td><td>${r.ok?'Matched':'Different'}</td></tr>`).join('')}</tbody></table><p class="equiv-why">Why: ranking prioritizes chemistry first, then particle size, pore size, dimensions, and format. Equivalent suggestions are suitable starting points and require method validation.</p>`}
function renderReplacementMatches(){let q=$('#replacementInput')?.value.trim()||'',h=$('#replacementResults');if(!h)return;if(!q){h.innerHTML='';return}let ms=findCompetitorMatches(q);h.innerHTML=ms.length?ms.map(({c})=>{let b=bestEquivalent(c);return`<div class="replacement-card"><div class="competitor-match"><h4>${esc(c.brand)} ${esc(c.name||c.family)}</h4><p class="code">${esc(c.partNumber||'')} · ${esc(c.phase)} · ${esc(c.particle)}um · ${esc(c.pore||'-')} · ${esc(c.diameter)} x ${esc(c.length)} mm</p><p>${esc(c.notes||'')}</p><small>${esc(c.source||'')}</small></div><div class="mme-match">${comparison(c,b)}</div></div>`}).join(''):`<div class="replacement-card"><div class="competitor-match"><h4>No competitor match yet</h4><p class="code">Try Agilent HC-C18 518915-902, Hitachi 889-0903, or Brownlee SPP C18 N9308417.</p></div></div>`}
function renderExpert(q,terms){let p=$('#expertPanel');if(!p)return;let tags=[...terms.map(t=>`Text: ${t}`),...Object.values(state.wizard).map(c=>c?.label).filter(Boolean)];p.hidden=!q&&!tags.length;if(!p.hidden){$('#expertSummary').textContent=tags.length?`Using ${tags.slice(0,4).join(', ')}${tags.length>4?'...':''}`:'Using catalog search';$('#expertTags').innerHTML=tags.map(t=>`<span class="expert-tag">${esc(t)}</span>`).join('')}}
function renderActive(sel,terms){let h=$('#activeFilters');if(!h)return;let tags=[...Object.entries(sel).filter(([,v])=>v).map(([f,v])=>`${f}: ${v}`),...terms.map(t=>`Search: ${t}`),...Object.values(state.wizard).map(c=>c?.label).filter(Boolean).map(l=>`Wizard: ${l}`),...Object.entries(state.tableFilters).filter(([,v])=>v).map(([f,v])=>`${f}: ${v}`)];h.innerHTML=tags.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}
document.addEventListener('DOMContentLoaded',init);
